services:
  under_construction_app:
    container_name: under_construction_container
    build: .
    image: under_construction_app
    ports: 
      - "4200:80"
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
