services:
  under_construction_app:
    container_name: under_construction_container
    build: .
    image: awsbuild
    ports: 
      - 4200
    expose:
      - 4200
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
