services:
  under_construction_app:
    container_name: under_construction_container
    build: .
    image: awsbuild-latest
    ports: 
      - "80:80"
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
